version: "1.0.1"

generic-lore:
- "&8&oTrade items cane be exchanged at"
- "&8&othe specified location. Faster"
- "&8&odeliveries give better profits"
- "&8&oand experience. Teleporting can"
- "&8&odestroy trade goods!"