version: "1.0.2"

# How close can you get before the waypoint auto
# clears itself
waypoint-clear-range: 4.5

# How close can you get before the waypoint snaps
# to its origin location
waypoint-snap-range: 14

# The style of the indicator when in motion
waypoint-indicator: "&b✖"

# The style of the indicator when still or snapped
# to origin. {0} is replaced by waypoint name
waypoint-indicator-snapped: "&b► {0} ◄"