name: Waypointer
version: ${project.version}
main: land.face.waypointer.WaypointerPlugin
depend: [Facecore, DecentHolograms]
api-version: 1.16

permissions:
  waypointer.clear:
    default: true
  waypointer.reload:
    default: false
  waypointer.set:
    default: op

commands:
  waypointer:
    description: Waypointing and waypointer accessories
    aliases: [waypoint, daway, wp]