name: Waypointer
version: ${project.version}
main: land.face.waypointer.WaypointerPlugin
depend: [Facecore, HolographicDisplays]
api-version: 1.15

permissions:
  waypointer.reload:
    default: false
  waypointer.set:
    default: op

commands:
  waypointer:
    description: Waypointing and waypointer accessories
    aliases: [waypoint, daway]